@BASE_URL=http://localhost:3000
@ORIGIN_ID=EkBBdi4gR292LiBWYWxhZGFyZXMsIDEwMDAgLSBDZW50cm8sIEJldGltIC0gTUcsIDM2NDEwLTAyNiwgQnJhc2lsIjESLwoUChIJqWNAFJLDpgARpsy5kCM5OC8Q6AcqFAoSCXkSTsuRw6YAETPuVaoFp4Tx
@DESTINATION_ID=ChIJTcM3WRKWpgARIBxMZeldEtM

### find a direction
GET {{BASE_URL}}/directions?originId={{ORIGIN_ID}}&destinationId={{DESTINATION_ID}}